### ISSUE TITLE
Contribute these themes to the Lite XL color theme repository and Catppuccino organization

### ISSUE THREAD

**Issue by SagXD** [Garbg/litexl_catppuccin#1]
Can you please add these themes to the [Lite XL color](https://github.com/lite-xl/lite-xl-colors) theme repository and the official catppuccin organization?

**Comment by SagXD** [comment]
I just noticed you already opened a [issue](https://github.com/catppuccin/catppuccin/issues/2092) on catppuccin.
Also If You don't have time then can I add themes to lite-xl theme repo?

**Comment by leofleeo** [comment]
You can add them to the lite-xl theme repo

**Comment by SagXD** [comment]
@Garbg OK I added
